In [2]:
import statistics
ls=[19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
ls.sort()
#sorting the list
print(ls)
mini=ls[0]
#taking min value from list
print(mini)
maxi=ls[len(ls)-1]
#taking max value from list
print(maxi)
ls.append(mini)
ls.append(maxi)
#appending values to the list
print(ls)
#median of the list
med=statistics.median(ls)
print(med)
#Getting length of the list
length=len(ls)
#Getting Sum of the list
sum_ls=sum(ls)
#Getting Avg of the list
avg=sum_ls/length
print(avg)
ra=(maxi-mini)
print(ra)

[19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
19
26
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 19, 26]
24.0
22.75
7


In [3]:
#Dog dictionary
dog={}
#Adding values to dict dog
dog['name']='bunny'
dog['color']='brown'
dog['breed']='lab'
dog['legs']='white'
dog['age']='5'
print(dog)
#Adding values to dict Student
student={}
student['first_name']='Pavan'
student['last_name']='Kalyan'
student['gender']='Male'
student['age']='24'
student['marital status']='Single'
student['skills']=['c','Python','java']
student['country']='USA'
student['city']='Kansas'
student['address']='3206'
print(student)
#length of the dict
print(len(student))
print(type(student['skills']))  
#Adding values to student['skills']
student['skills']=['unix','C','Html']
print(student)
keys=student.keys()
print(list(keys))
values=student.values()
print(list(values))

{'name': 'bunny', 'color': 'brown', 'breed': 'lab', 'legs': 'white', 'age': '5'}
{'first_name': 'Pavan', 'last_name': 'Kalyan', 'gender': 'Male', 'age': '24', 'marital status': 'Single', 'skills': ['c', 'Python', 'java'], 'country': 'USA', 'city': 'Kansas', 'address': '3206'}
9
<class 'list'>
{'first_name': 'Pavan', 'last_name': 'Kalyan', 'gender': 'Male', 'age': '24', 'marital status': 'Single', 'skills': ['unix', 'C', 'Html'], 'country': 'USA', 'city': 'Kansas', 'address': '3206'}
['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'country', 'city', 'address']
['Pavan', 'Kalyan', 'Male', '24', 'Single', ['unix', 'C', 'Html'], 'USA', 'Kansas', '3206']


In [4]:
brothers_tuple=('ram','bheeam')
sisters_tuple=('yogi','sravani')
#Merging Sibling 
siblings=brothers_tuple+sisters_tuple
print(siblings)
print(len(siblings))
siblings=list(siblings)
#appending parents to tuple
siblings.append('Gandhi')
siblings.append('Sailaja')
family_members=tuple(siblings)
family_members

('ram', 'bheeam', 'yogi', 'sravani')
4


('ram', 'bheeam', 'yogi', 'sravani', 'Gandhi', 'Sailaja')

In [19]:
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]
print(len(it_companies))
#Adding Company name to it_companies
it_companies.add('Twitter')
#Adding Mutiple compaines to tuple
new = ['Cognizant','TCS','Infosys','Wipro']
it_companies.update(new)
print(it_companies)
#Removing a Company from tuple
it_companies.remove('Wipro')
it_companies.discard('Wipro')
print(it_companies)
'''
Discard() will Removes the element from the set only if the element is present in the set.if not it will not raise an error
Remove() will work same as Discard() but if element is not present in the list it will throw a error
'''
#joing 2 tuples
print(A.union(B))
#Intersection of 2 tuples
print(A.intersection(B))
#checking A is Subset of b
print(A.issubset(B))
#checking a is disjoint set or not
print(A.isdisjoint(B))
print(A.union(B))
print(B.union(A))
print(A.symmetric_difference(B))
del it_companies
del A
del B
print(len(age))
age_set=set(age)
print(len(age_set))

7
{'Google', 'IBM', 'Apple', 'Microsoft', 'Facebook', 'Wipro', 'Cognizant', 'TCS', 'Oracle', 'Amazon', 'Infosys', 'Twitter'}
{'Google', 'IBM', 'Apple', 'Microsoft', 'Facebook', 'Cognizant', 'TCS', 'Oracle', 'Amazon', 'Infosys', 'Twitter'}
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26}
True
False
{19, 20, 22, 24, 25, 26, 27, 28}
{19, 20, 22, 24, 25, 26, 27, 28}
{27, 28}
8
5


In [20]:
radius = 30
#defining radius = 30
_area_of_circle_= (3.14)*(radius)*(radius)
#printing area of circle
print(_area_of_circle_)
_circum_of_circle_ = (2)*(3.14)*(radius)
print(_circum_of_circle_)
#reading input from user
r=int(input("Enter the value"))
print((3.14)*(r)*(r))


2826.0
Enter the value40
5024.0


In [22]:
s = 'I am a teacher and I love to inspire and teach people'
#split() used to split it into listby space
s=s.split(' ')
print(set(s))
print(len(set(s)))

{'a', 'teacher', 'love', 'to', 'I', 'inspire', 'people', 'and', 'teach', 'am'}
10


In [25]:
#\t is used to tab space
print("Name\t\tAge\tCountry\tCity")
print("Asabeneh\t250\tFinland\tHelsinki")

Name		Age	Country	City
Asabeneh	250	Finland	Helsinki


In [36]:
radius = 10
PI = 3.14
area=(3.14)*(radius)*(radius)
#formatting radius
print("radius = {radius}".format(radius = 10))
print("area = {PI}*radius**2".format(PI = 3.14))
print("\"The area of a circle with radius {radius} is {area} meters square""\"".format(radius=10,area = (3.14)*(radius)*(radius)))


radius = 10
area = 3.14*radius**2
"The area of a circle with radius 10 is 314.0 meters square"


In [50]:
import math
#reading input from user
x = [int(x) for x in input().split(',')]
ls =[]
for i in x:
    #converting lbs to Kgs
    ls.append(round((i/2.205),2))
print(ls)

150, 155, 145, 148
[68.03, 70.29, 65.76, 67.12]


In [10]:
import numpy as np
from sklearn.model_selection import train_test_split
#Importing for implementing knn
from sklearn.neighbors import KNeighborsClassifier
#Splitting data into training and testing data
a=np.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
b=np.array([0,0,1,1,1,0,0,0])
a_train,a_test,b_train,b_test=train_test_split(a,b,test_size=0.5,random_state=0,shuffle=False)
print(a_train)
print(b_train)
#implementing knn with 3
n=KNeighborsClassifier(n_neighbors=3)
#fitting the knn from the training data
n.fit(a_train,b_train)
b_pred=n.predict(a_test)
print(b_pred)

[[1 0]
 [2 0]
 [3 0]
 [6 0]]
[0 0 1 1]
[1 1 1 1]
